Vagrant.configure("2") do |config|
    config.vm.box = "opensuse/Tumbleweed.x86_64"
    config.vm.box_version = "1.0.20210119"
   
    config.vm.define :podman do |podman|
      podman.vm.host_name="podman"
      podman.vm.network "private_network", ip: "192.168.56.10", bridge: "eno1"
      podman.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
end      
    config.vm.define :docker do |docker|
        docker.vm.host_name="docker"
        docker.vm.network "private_network", ip: "192.168.56.20", bridge: "eno1"
        docker.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end
end
  