Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
   
    config.vm.define :podman do |podman|
        podman.vm.host_name="podman"
        podman.vm.network "private_network", ip: "192.168.56.30", bridge: "eno1"
        podman.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
    end
end
    config.vm.define :docker do |docker|
        docker.vm.host_name="docker"
        docker.vm.network "private_network", ip: "192.168.56.35", bridge: "eno1"
        docker.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end
end